// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// actor_events
List actor_events(IntegerMatrix el, int q);
RcppExport SEXP bitriad_actor_events(SEXP elSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type el(elSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(actor_events(el, q));
    return rcpp_result_gen;
END_RCPP
}
// event_actors
List event_actors(IntegerMatrix el, int a);
RcppExport SEXP bitriad_event_actors(SEXP elSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type el(elSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(event_actors(el, a));
    return rcpp_result_gen;
END_RCPP
}
// actor_actors
List actor_actors(IntegerMatrix el, int q);
RcppExport SEXP bitriad_actor_actors(SEXP elSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type el(elSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(actor_actors(el, q));
    return rcpp_result_gen;
END_RCPP
}
// wedges_x0w0m0c0
List wedges_x0w0m0c0(IntegerMatrix el, int q);
RcppExport SEXP bitriad_wedges_x0w0m0c0(SEXP elSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type el(elSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(wedges_x0w0m0c0(el, q));
    return rcpp_result_gen;
END_RCPP
}
// wedges_x0w0m0c1
List wedges_x0w0m0c1(IntegerMatrix el, int q);
RcppExport SEXP bitriad_wedges_x0w0m0c1(SEXP elSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type el(elSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(wedges_x0w0m0c1(el, q));
    return rcpp_result_gen;
END_RCPP
}
// wedges_x0w0m0c2
List wedges_x0w0m0c2(IntegerMatrix el, int q);
RcppExport SEXP bitriad_wedges_x0w0m0c2(SEXP elSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type el(elSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(wedges_x0w0m0c2(el, q));
    return rcpp_result_gen;
END_RCPP
}
// wedges_x0w0m1c0
List wedges_x0w0m1c0(IntegerMatrix el, int q);
RcppExport SEXP bitriad_wedges_x0w0m1c0(SEXP elSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type el(elSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(wedges_x0w0m1c0(el, q));
    return rcpp_result_gen;
END_RCPP
}
// wedges_x0w0m1c1
List wedges_x0w0m1c1(IntegerMatrix el, int q);
RcppExport SEXP bitriad_wedges_x0w0m1c1(SEXP elSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type el(elSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(wedges_x0w0m1c1(el, q));
    return rcpp_result_gen;
END_RCPP
}
// wedges_x0w0m1c2
List wedges_x0w0m1c2(IntegerMatrix el, int q);
RcppExport SEXP bitriad_wedges_x0w0m1c2(SEXP elSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type el(elSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(wedges_x0w0m1c2(el, q));
    return rcpp_result_gen;
END_RCPP
}
// wedges_x0w0m2c0
List wedges_x0w0m2c0(IntegerMatrix el, int q);
RcppExport SEXP bitriad_wedges_x0w0m2c0(SEXP elSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type el(elSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(wedges_x0w0m2c0(el, q));
    return rcpp_result_gen;
END_RCPP
}
// wedges_x0w0m2c1
List wedges_x0w0m2c1(IntegerMatrix el, int q);
RcppExport SEXP bitriad_wedges_x0w0m2c1(SEXP elSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type el(elSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(wedges_x0w0m2c1(el, q));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"bitriad_actor_events", (DL_FUNC) &bitriad_actor_events, 2},
    {"bitriad_event_actors", (DL_FUNC) &bitriad_event_actors, 2},
    {"bitriad_actor_actors", (DL_FUNC) &bitriad_actor_actors, 2},
    {"bitriad_wedges_x0w0m0c0", (DL_FUNC) &bitriad_wedges_x0w0m0c0, 2},
    {"bitriad_wedges_x0w0m0c1", (DL_FUNC) &bitriad_wedges_x0w0m0c1, 2},
    {"bitriad_wedges_x0w0m0c2", (DL_FUNC) &bitriad_wedges_x0w0m0c2, 2},
    {"bitriad_wedges_x0w0m1c0", (DL_FUNC) &bitriad_wedges_x0w0m1c0, 2},
    {"bitriad_wedges_x0w0m1c1", (DL_FUNC) &bitriad_wedges_x0w0m1c1, 2},
    {"bitriad_wedges_x0w0m1c2", (DL_FUNC) &bitriad_wedges_x0w0m1c2, 2},
    {"bitriad_wedges_x0w0m2c0", (DL_FUNC) &bitriad_wedges_x0w0m2c0, 2},
    {"bitriad_wedges_x0w0m2c1", (DL_FUNC) &bitriad_wedges_x0w0m2c1, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_bitriad(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
