# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wedges_x0w0m0c0 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m0c0', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m0c1 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m0c1', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m0c2 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m0c2', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m1c0 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m1c0', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m1c1 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m1c1', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m1c2 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m1c2', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m2c0 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m2c0', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m2c1 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m2c1', PACKAGE = 'bitriad', el, q)
}

#' @rdname combinatorial_bijections
#' @export
index_subset <- function(i) {
    .Call('_bitriad_index_subset', PACKAGE = 'bitriad', i)
}

#' @rdname combinatorial_bijections
#' @export
subset_index <- function(vec) {
    .Call('_bitriad_subset_index', PACKAGE = 'bitriad', vec)
}

#' @rdname combinatorial_bijections
#' @export
subset_partition <- function(vec) {
    .Call('_bitriad_subset_partition', PACKAGE = 'bitriad', vec)
}

#' @rdname combinatorial_bijections
#' @export
partition_subset <- function(lambda) {
    .Call('_bitriad_partition_subset', PACKAGE = 'bitriad', lambda)
}

#' @rdname combinatorial_bijections
#' @export
index_partition <- function(i) {
    .Call('_bitriad_index_partition', PACKAGE = 'bitriad', i)
}

#' @rdname combinatorial_bijections
#' @export
partition_index <- function(lambda) {
    .Call('_bitriad_partition_index', PACKAGE = 'bitriad', lambda)
}

triad_census_batagelj_mrvar_C <- function(el) {
    .Call('_bitriad_triad_census_batagelj_mrvar_C', PACKAGE = 'bitriad', el)
}

triad_census_batagelj_mrvar_alt_C <- function(el, actors, max_weight) {
    .Call('_bitriad_triad_census_batagelj_mrvar_alt_C', PACKAGE = 'bitriad', el, actors, max_weight)
}

triad_census_difference_batagelj_mrvar_C <- function(el) {
    .Call('_bitriad_triad_census_difference_batagelj_mrvar_C', PACKAGE = 'bitriad', el)
}

triad_census_binary_batagelj_mrvar_C <- function(el) {
    .Call('_bitriad_triad_census_binary_batagelj_mrvar_C', PACKAGE = 'bitriad', el)
}

wedges_from_binary_census_C <- function(census, alcove, wedge, maps, congruence) {
    .Call('_bitriad_wedges_from_binary_census_C', PACKAGE = 'bitriad', census, alcove, wedge, maps, congruence)
}

