# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

actor_events <- function(el, q) {
    .Call('bitriad_actor_events', PACKAGE = 'bitriad', el, q)
}

event_actors <- function(el, a) {
    .Call('bitriad_event_actors', PACKAGE = 'bitriad', el, a)
}

actor_actors <- function(el, q) {
    .Call('bitriad_actor_actors', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m0c0 <- function(el, q) {
    .Call('bitriad_wedges_x0w0m0c0', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m0c1 <- function(el, q) {
    .Call('bitriad_wedges_x0w0m0c1', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m0c2 <- function(el, q) {
    .Call('bitriad_wedges_x0w0m0c2', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m1c0 <- function(el, q) {
    .Call('bitriad_wedges_x0w0m1c0', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m1c1 <- function(el, q) {
    .Call('bitriad_wedges_x0w0m1c1', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m1c2 <- function(el, q) {
    .Call('bitriad_wedges_x0w0m1c2', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m2c0 <- function(el, q) {
    .Call('bitriad_wedges_x0w0m2c0', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m2c1 <- function(el, q) {
    .Call('bitriad_wedges_x0w0m2c1', PACKAGE = 'bitriad', el, q)
}

