# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

centered_triads <- function(el, q) {
    .Call('_bitriad_centered_triads', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m0c0 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m0c0', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m0c1 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m0c1', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m0c2 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m0c2', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m1c0 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m1c0', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m1c1 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m1c1', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m1c2 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m1c2', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m2c0 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m2c0', PACKAGE = 'bitriad', el, q)
}

wedges_x0w0m2c1 <- function(el, q) {
    .Call('_bitriad_wedges_x0w0m2c1', PACKAGE = 'bitriad', el, q)
}

dynamic_wedges_x0w0m20c02 <- function(el, t, q, memory, wedge_gap, close_after, close_before) {
    .Call('_bitriad_dynamic_wedges_x0w0m20c02', PACKAGE = 'bitriad', el, t, q, memory, wedge_gap, close_after, close_before)
}

dynamic_wedges_x0w0m0c0 <- function(el, t, q, memory, wedge_gap, close_after, close_before) {
    .Call('_bitriad_dynamic_wedges_x0w0m0c0', PACKAGE = 'bitriad', el, t, q, memory, wedge_gap, close_after, close_before)
}

triad_census_full_batagelj_mrvar_C <- function(el, na) {
    .Call('_bitriad_triad_census_full_batagelj_mrvar_C', PACKAGE = 'bitriad', el, na)
}

triad_census_full_batagelj_mrvar_long_C <- function(el, na) {
    .Call('_bitriad_triad_census_full_batagelj_mrvar_long_C', PACKAGE = 'bitriad', el, na)
}

triad_census_difference_batagelj_mrvar_C <- function(el, na) {
    .Call('_bitriad_triad_census_difference_batagelj_mrvar_C', PACKAGE = 'bitriad', el, na)
}

triad_census_difference_batagelj_mrvar_long_C <- function(el, na) {
    .Call('_bitriad_triad_census_difference_batagelj_mrvar_long_C', PACKAGE = 'bitriad', el, na)
}

triad_census_binary_batagelj_mrvar_C <- function(el, na) {
    .Call('_bitriad_triad_census_binary_batagelj_mrvar_C', PACKAGE = 'bitriad', el, na)
}

triad_census_binary_batagelj_mrvar_long_C <- function(el, na) {
    .Call('_bitriad_triad_census_binary_batagelj_mrvar_long_C', PACKAGE = 'bitriad', el, na)
}

wedges_from_binary_census_C <- function(census, alcove, wedge, maps, congruence) {
    .Call('_bitriad_wedges_from_binary_census_C', PACKAGE = 'bitriad', census, alcove, wedge, maps, congruence)
}

#' @rdname combinatorial_bijections
#' @export
index_subset <- function(i) {
    .Call('_bitriad_index_subset', PACKAGE = 'bitriad', i)
}

#' @rdname combinatorial_bijections
#' @export
subset_index <- function(vec) {
    .Call('_bitriad_subset_index', PACKAGE = 'bitriad', vec)
}

#' @rdname combinatorial_bijections
#' @export
subset_partition <- function(vec) {
    .Call('_bitriad_subset_partition', PACKAGE = 'bitriad', vec)
}

#' @rdname combinatorial_bijections
#' @export
partition_subset <- function(lambda) {
    .Call('_bitriad_partition_subset', PACKAGE = 'bitriad', lambda)
}

#' @rdname combinatorial_bijections
#' @export
index_partition <- function(i) {
    .Call('_bitriad_index_partition', PACKAGE = 'bitriad', i)
}

#' @rdname combinatorial_bijections
#' @export
partition_index <- function(lambda) {
    .Call('_bitriad_partition_index', PACKAGE = 'bitriad', lambda)
}

